-- MySQL Script generated by MySQL Workbench
-- 03/23/17 01:54:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` DEFAULT CHARACTER SET utf8 ;
USE `db` ;

-- -----------------------------------------------------
-- Table `db`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`course` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(20) NULL DEFAULT NULL,
  `teacher` VARCHAR(20) NULL DEFAULT NULL,
  `year` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`student` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `birthdate` DATE NULL DEFAULT NULL,
  `address` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db`.`enroll`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`enroll` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_student` INT(11) NOT NULL,
  `id_curs` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_student_idx` (`id_student` ASC),
  INDEX `id_course_idx` (`id_curs` ASC),
  CONSTRAINT `id_course`
    FOREIGN KEY (`id_curs`)
    REFERENCES `db`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_student`
    FOREIGN KEY (`id_student`)
    REFERENCES `db`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
